'use client';

import { useEffect, useState, useCallback } from 'react';
import { useRouter } from 'next/navigation';
import {
  getAdminDailyContent,
  deleteDailyContent,
  autoGenerateDailyContent,
  getDailyContentStats,
} from '@/lib/api';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Switch } from '@/components/ui/switch';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import {
  IconLoader2,
  IconPlus,
  IconDots,
  IconEdit,
  IconTrash,
  IconCalendar,
  IconList,
  IconQuote,
  IconBrain,
  IconWind,
  IconSparkles,
  IconChevronLeft,
  IconChevronRight,
  IconWand,
} from '@tabler/icons-react';
import { toast } from 'sonner';
import {
  format,
  startOfMonth,
  endOfMonth,
  eachDayOfInterval,
  isSameMonth,
  isToday,
  addMonths,
  subMonths,
  startOfWeek,
  endOfWeek,
} from 'date-fns';
import { tr } from 'date-fns/locale';

interface DailyContentItem {
  id: string;
  date: string;
  quote?: {
    id: string;
    text: string;
    author?: string;
  };
  meditation?: {
    id: string;
    title: string;
    coverImage?: string;
  };
  breathwork?: {
    id: string;
    title: string;
  };
  tip?: string;
  challenge?: string;
  isPublished: boolean;
  createdAt: string;
}

interface Stats {
  total: number;
  published: number;
  upcoming: number;
}

export function DailyContentManager() {
  const router = useRouter();
  const [content, setContent] = useState<DailyContentItem[]>([]);
  const [stats, setStats] = useState<Stats | null>(null);
  const [loading, setLoading] = useState(true);
  const [deleteDialog, setDeleteDialog] = useState(false);
  const [generateDialog, setGenerateDialog] = useState(false);
  const [selectedContent, setSelectedContent] = useState<DailyContentItem | null>(null);
  const [generating, setGenerating] = useState(false);

  // View and filter state
  const [viewType, setViewType] = useState<'calendar' | 'list'>('calendar');
  const [currentMonth, setCurrentMonth] = useState(new Date());
  const [publishedFilter, setPublishedFilter] = useState('');

  const loadContent = useCallback(async () => {
    setLoading(true);
    try {
      const start = startOfMonth(currentMonth);
      const end = endOfMonth(currentMonth);

      const params: any = {
        startDate: format(start, 'yyyy-MM-dd'),
        endDate: format(end, 'yyyy-MM-dd'),
      };
      if (publishedFilter) params.isPublished = publishedFilter === 'true';

      const data = await getAdminDailyContent(params);
      setContent(data.content || data.dailyContent || []);

      // Load stats
      try {
        const statsData = await getDailyContentStats();
        setStats(statsData);
      } catch {
        // Stats endpoint may not exist
      }
    } catch (error) {
      console.error('Failed to load daily content:', error);
      toast.error('Günlük içerik yüklenemedi');
    } finally {
      setLoading(false);
    }
  }, [currentMonth, publishedFilter]);

  useEffect(() => {
    loadContent();
  }, [loadContent]);

  const handleDelete = async () => {
    if (!selectedContent) return;
    try {
      await deleteDailyContent(selectedContent.id);
      toast.success('Günlük içerik silindi');
      setDeleteDialog(false);
      loadContent();
    } catch (error: any) {
      toast.error(error.response?.data?.error || 'Silme işlemi başarısız');
    }
  };

  const handleAutoGenerate = async () => {
    setGenerating(true);
    try {
      const start = startOfMonth(currentMonth);
      const end = endOfMonth(currentMonth);

      await autoGenerateDailyContent({
        startDate: format(start, 'yyyy-MM-dd'),
        endDate: format(end, 'yyyy-MM-dd'),
      });
      toast.success('İçerikler otomatik oluşturuldu');
      setGenerateDialog(false);
      loadContent();
    } catch (error: any) {
      toast.error(error.response?.data?.error || 'Otomatik oluşturma başarısız');
    } finally {
      setGenerating(false);
    }
  };

  const getContentForDate = (date: Date) => {
    const dateStr = format(date, 'yyyy-MM-dd');
    return content.find((c) => c.date.startsWith(dateStr));
  };

  const truncateText = (text: string, maxLength: number) => {
    if (text.length <= maxLength) return text;
    return text.substring(0, maxLength) + '...';
  };

  // Generate calendar days
  const monthStart = startOfMonth(currentMonth);
  const monthEnd = endOfMonth(currentMonth);
  const calendarStart = startOfWeek(monthStart, { weekStartsOn: 1 });
  const calendarEnd = endOfWeek(monthEnd, { weekStartsOn: 1 });
  const calendarDays = eachDayOfInterval({ start: calendarStart, end: calendarEnd });

  return (
    <div className="space-y-4">
      {/* Stats */}
      {stats && (
        <div className="grid grid-cols-3 gap-4">
          <Card>
            <CardContent className="p-4">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm text-muted-foreground">Toplam</p>
                  <p className="text-2xl font-bold">{stats.total}</p>
                </div>
                <IconCalendar className="h-8 w-8 text-violet-500" />
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="p-4">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm text-muted-foreground">Yayında</p>
                  <p className="text-2xl font-bold text-green-600">{stats.published}</p>
                </div>
                <IconSparkles className="h-8 w-8 text-green-500" />
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="p-4">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm text-muted-foreground">Gelecek</p>
                  <p className="text-2xl font-bold text-blue-600">{stats.upcoming}</p>
                </div>
                <IconCalendar className="h-8 w-8 text-blue-500" />
              </div>
            </CardContent>
          </Card>
        </div>
      )}

      {/* Controls */}
      <Card>
        <CardContent className="p-4">
          <div className="flex items-center justify-between gap-4">
            <div className="flex items-center gap-4">
              {/* Month Navigation */}
              <div className="flex items-center gap-2">
                <Button
                  variant="outline"
                  size="icon"
                  onClick={() => setCurrentMonth(subMonths(currentMonth, 1))}
                >
                  <IconChevronLeft className="h-4 w-4" />
                </Button>
                <span className="font-medium min-w-[150px] text-center">
                  {format(currentMonth, 'MMMM yyyy', { locale: tr })}
                </span>
                <Button
                  variant="outline"
                  size="icon"
                  onClick={() => setCurrentMonth(addMonths(currentMonth, 1))}
                >
                  <IconChevronRight className="h-4 w-4" />
                </Button>
              </div>

              {/* View Toggle */}
              <Tabs value={viewType} onValueChange={(v) => setViewType(v as 'calendar' | 'list')}>
                <TabsList>
                  <TabsTrigger value="calendar">
                    <IconCalendar className="h-4 w-4 mr-1" />
                    Takvim
                  </TabsTrigger>
                  <TabsTrigger value="list">
                    <IconList className="h-4 w-4 mr-1" />
                    Liste
                  </TabsTrigger>
                </TabsList>
              </Tabs>

              <Select value={publishedFilter} onValueChange={setPublishedFilter}>
                <SelectTrigger className="w-[140px]">
                  <SelectValue placeholder="Durum" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">Tümü</SelectItem>
                  <SelectItem value="true">Yayında</SelectItem>
                  <SelectItem value="false">Taslak</SelectItem>
                </SelectContent>
              </Select>
            </div>

            <div className="flex items-center gap-2">
              <Button
                variant="outline"
                onClick={() => setGenerateDialog(true)}
              >
                <IconWand className="h-4 w-4 mr-2" />
                Otomatik Oluştur
              </Button>
              <Button onClick={() => router.push(`/dashboard/wellness/daily-content/${format(new Date(), 'yyyy-MM-dd')}`)}>
                <IconPlus className="h-4 w-4 mr-2" />
                Yeni İçerik
              </Button>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Content */}
      {loading ? (
        <Card>
          <CardContent className="p-12">
            <div className="flex items-center justify-center">
              <IconLoader2 className="h-8 w-8 animate-spin" />
            </div>
          </CardContent>
        </Card>
      ) : viewType === 'calendar' ? (
        /* Calendar View */
        <Card>
          <CardContent className="p-4">
            {/* Weekday Headers */}
            <div className="grid grid-cols-7 gap-1 mb-2">
              {['Pzt', 'Sal', 'Çar', 'Per', 'Cum', 'Cmt', 'Paz'].map((day) => (
                <div
                  key={day}
                  className="text-center text-sm font-medium text-muted-foreground py-2"
                >
                  {day}
                </div>
              ))}
            </div>

            {/* Calendar Grid */}
            <div className="grid grid-cols-7 gap-1">
              {calendarDays.map((day) => {
                const dayContent = getContentForDate(day);
                const isCurrentMonth = isSameMonth(day, currentMonth);
                const isTodayDate = isToday(day);

                return (
                  <div
                    key={day.toISOString()}
                    className={`min-h-[120px] p-2 rounded-lg border cursor-pointer transition-colors hover:bg-muted/50 ${
                      !isCurrentMonth ? 'opacity-40' : ''
                    } ${isTodayDate ? 'border-primary bg-primary/5' : 'border-border'}`}
                    onClick={() =>
                      router.push(
                        `/dashboard/wellness/daily-content/${format(day, 'yyyy-MM-dd')}`
                      )
                    }
                  >
                    <div className="flex items-center justify-between mb-1">
                      <span
                        className={`text-sm font-medium ${
                          isTodayDate ? 'text-primary' : ''
                        }`}
                      >
                        {format(day, 'd')}
                      </span>
                      {dayContent?.isPublished && (
                        <Badge variant="secondary" className="text-xs px-1 bg-green-100 text-green-700">
                          Yayında
                        </Badge>
                      )}
                    </div>

                    {dayContent && (
                      <div className="space-y-1">
                        {dayContent.quote && (
                          <div className="flex items-center gap-1 text-xs text-muted-foreground">
                            <IconQuote className="h-3 w-3" />
                            <span className="truncate">Söz</span>
                          </div>
                        )}
                        {dayContent.meditation && (
                          <div className="flex items-center gap-1 text-xs text-muted-foreground">
                            <IconBrain className="h-3 w-3" />
                            <span className="truncate">{dayContent.meditation.title}</span>
                          </div>
                        )}
                        {dayContent.breathwork && (
                          <div className="flex items-center gap-1 text-xs text-muted-foreground">
                            <IconWind className="h-3 w-3" />
                            <span className="truncate">{dayContent.breathwork.title}</span>
                          </div>
                        )}
                        {dayContent.tip && (
                          <div className="flex items-center gap-1 text-xs text-muted-foreground">
                            <IconSparkles className="h-3 w-3" />
                            <span className="truncate">İpucu</span>
                          </div>
                        )}
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          </CardContent>
        </Card>
      ) : (
        /* List View */
        <Card>
          <CardContent className="p-0">
            {content.length === 0 ? (
              <div className="text-center py-12 text-muted-foreground">
                Bu ay için içerik bulunamadı
              </div>
            ) : (
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Tarih</TableHead>
                    <TableHead>Günün Sözü</TableHead>
                    <TableHead>Meditasyon</TableHead>
                    <TableHead>Nefes</TableHead>
                    <TableHead>İpucu</TableHead>
                    <TableHead>Yayında</TableHead>
                    <TableHead className="w-[70px]"></TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {content
                    .sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime())
                    .map((item) => (
                      <TableRow key={item.id}>
                        <TableCell>
                          <span className="font-medium">
                            {format(new Date(item.date), 'd MMMM yyyy', { locale: tr })}
                          </span>
                        </TableCell>
                        <TableCell>
                          {item.quote ? (
                            <div className="max-w-[200px]">
                              <p className="text-sm truncate">&quot;{item.quote.text}&quot;</p>
                              {item.quote.author && (
                                <p className="text-xs text-muted-foreground">- {item.quote.author}</p>
                              )}
                            </div>
                          ) : (
                            <span className="text-muted-foreground">-</span>
                          )}
                        </TableCell>
                        <TableCell>
                          {item.meditation ? (
                            <span className="text-sm">{item.meditation.title}</span>
                          ) : (
                            <span className="text-muted-foreground">-</span>
                          )}
                        </TableCell>
                        <TableCell>
                          {item.breathwork ? (
                            <span className="text-sm">{item.breathwork.title}</span>
                          ) : (
                            <span className="text-muted-foreground">-</span>
                          )}
                        </TableCell>
                        <TableCell>
                          {item.tip ? (
                            <span className="text-sm">{truncateText(item.tip, 50)}</span>
                          ) : (
                            <span className="text-muted-foreground">-</span>
                          )}
                        </TableCell>
                        <TableCell>
                          <Switch checked={item.isPublished} disabled />
                        </TableCell>
                        <TableCell>
                          <DropdownMenu>
                            <DropdownMenuTrigger asChild>
                              <Button variant="ghost" size="icon" className="h-8 w-8">
                                <IconDots className="h-4 w-4" />
                              </Button>
                            </DropdownMenuTrigger>
                            <DropdownMenuContent align="end">
                              <DropdownMenuItem
                                onClick={() =>
                                  router.push(
                                    `/dashboard/wellness/daily-content/${format(
                                      new Date(item.date),
                                      'yyyy-MM-dd'
                                    )}`
                                  )
                                }
                              >
                                <IconEdit className="mr-2 h-4 w-4" />
                                Düzenle
                              </DropdownMenuItem>
                              <DropdownMenuSeparator />
                              <DropdownMenuItem
                                className="text-destructive"
                                onClick={() => {
                                  setSelectedContent(item);
                                  setDeleteDialog(true);
                                }}
                              >
                                <IconTrash className="mr-2 h-4 w-4" />
                                Sil
                              </DropdownMenuItem>
                            </DropdownMenuContent>
                          </DropdownMenu>
                        </TableCell>
                      </TableRow>
                    ))}
                </TableBody>
              </Table>
            )}
          </CardContent>
        </Card>
      )}

      {/* Delete Dialog */}
      <AlertDialog open={deleteDialog} onOpenChange={setDeleteDialog}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Günlük İçerik Sil</AlertDialogTitle>
            <AlertDialogDescription>
              Bu günün içeriğini silmek istediğinize emin misiniz? Bu işlem geri
              alınamaz.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>İptal</AlertDialogCancel>
            <AlertDialogAction
              onClick={handleDelete}
              className="bg-destructive text-destructive-foreground"
            >
              Sil
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

      {/* Auto Generate Dialog */}
      <AlertDialog open={generateDialog} onOpenChange={setGenerateDialog}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Otomatik İçerik Oluştur</AlertDialogTitle>
            <AlertDialogDescription>
              {format(currentMonth, 'MMMM yyyy', { locale: tr })} için otomatik
              içerik oluşturulsun mu? Mevcut içerikler korunacak, sadece boş günler
              doldurulacaktır.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>İptal</AlertDialogCancel>
            <AlertDialogAction onClick={handleAutoGenerate} disabled={generating}>
              {generating ? (
                <>
                  <IconLoader2 className="mr-2 h-4 w-4 animate-spin" />
                  Oluşturuluyor...
                </>
              ) : (
                <>
                  <IconWand className="mr-2 h-4 w-4" />
                  Oluştur
                </>
              )}
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
}
