import {
  IconAlertTriangle,
  IconArrowRight,
  IconCheck,
  IconChevronLeft,
  IconChevronRight,
  IconCommand,
  IconCreditCard,
  IconFile,
  IconFileText,
  IconHelpCircle,
  IconPhoto,
  IconDeviceLaptop,
  IconLayoutDashboard,
  IconLoader2,
  IconLogin,
  IconLogout,
  IconProps,
  IconShoppingBag,
  IconMoon,
  IconDotsVertical,
  IconPizza,
  IconPlus,
  IconSettings,
  IconSun,
  IconTrash,
  IconBrandTwitter,
  IconUser,
  IconUserCircle,
  IconUserEdit,
  IconUserX,
  IconUsers,
  IconX,
  IconLayoutKanban,
  IconBrandGithub,
  // Yoga App Icons
  IconYoga,
  IconStretching2,
  IconFlower,
  IconTrophy,
  IconCalendarEvent,
  IconChartBar,
  IconShield,
  IconCash,
  IconReceipt,
  IconVideo,
  IconActivity,
  IconReportAnalytics,
  IconHistory,
  // Community Icons
  IconUsersGroup,
  IconFolder,
  IconMessage,
  IconFlag,
  // Notifications
  IconBellRinging,
  // Gamification Icons
  IconMedal,
  IconTargetArrow,
  IconChartLine,
  IconGift,
  IconShoppingCart,
  // Podcast
  IconMicrophone,
  // New Icons for Sprint 9-10
  IconPlaylist,
  IconCategory,
  IconTemplate,
  IconRocket,
  IconChartPie,
  IconMoodSmile,
  IconTarget,
  IconBell,
  IconHeart,
  IconBrain,
  IconWind,
  IconClock,
  IconSunrise,
  IconBook,
  IconPencil,
  IconMusic,
  IconQuote,
  IconEdit
} from '@tabler/icons-react';

export type Icon = React.ComponentType<IconProps>;

export const Icons = {
  dashboard: IconLayoutDashboard,
  logo: IconCommand,
  login: IconLogin,
  logout: IconLogout,
  close: IconX,
  product: IconShoppingBag,
  spinner: IconLoader2,
  kanban: IconLayoutKanban,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  trash: IconTrash,
  employee: IconUserX,
  post: IconFileText,
  page: IconFile,
  userPen: IconUserEdit,
  user2: IconUserCircle,
  media: IconPhoto,
  settings: IconSettings,
  billing: IconCreditCard,
  ellipsis: IconDotsVertical,
  add: IconPlus,
  warning: IconAlertTriangle,
  user: IconUser,
  users: IconUsers,
  arrowRight: IconArrowRight,
  help: IconHelpCircle,
  pizza: IconPizza,
  sun: IconSun,
  moon: IconMoon,
  laptop: IconDeviceLaptop,
  github: IconBrandGithub,
  twitter: IconBrandTwitter,
  check: IconCheck,
  // Yoga App Icons
  programs: IconYoga,
  classes: IconStretching2,
  poses: IconFlower,
  challenges: IconTrophy,
  calendar: IconCalendarEvent,
  analytics: IconChartBar,
  moderation: IconShield,
  payments: IconCash,
  subscriptions: IconReceipt,
  liveStreams: IconVideo,
  activity: IconActivity,
  instructors: IconReportAnalytics,
  auditLogs: IconHistory,
  // Community Icons
  community: IconUsersGroup,
  folder: IconFolder,
  message: IconMessage,
  flag: IconFlag,
  // Notifications
  notifications: IconBellRinging,
  // Gamification
  gamification: IconMedal,
  achievements: IconTrophy,
  quests: IconTargetArrow,
  leaderboard: IconChartLine,
  shop: IconShoppingCart,
  dailyRewards: IconGift,
  // Podcast
  podcast: IconMicrophone,
  // New Icons for Sprint 9-10
  playlist: IconPlaylist,
  userContent: IconCategory,
  template: IconTemplate,
  rocket: IconRocket,
  chart: IconChartPie,
  mood: IconMoodSmile,
  target: IconTarget,
  bell: IconBell,
  wellness: IconHeart,
  meditation: IconBrain,
  breathwork: IconWind,
  timer: IconClock,
  dailyContent: IconSunrise,
  journal: IconBook,
  quotes: IconPencil,
  // Sidebar icon aliases
  heart: IconHeart,
  wind: IconWind,
  music: IconMusic,
  clock: IconClock,
  quote: IconQuote,
  book: IconBook,
  edit: IconEdit
};
